import { useEffect, useMemo, useRef, useState } from 'react'
import { Download, Pencil, RotateCcw, Save, Upload, X } from 'lucide-react'
import { ApiError, fetchOperatingPlan, fetchPlanningTemplate, importPlanningInputs, previewDashboard } from '@/api/client'
import type { BrandFilter, DashboardResponse, MarketFilter, PlanVariant, PlanningInputRow, PlanningInputSource, WorkforceCapacityInputRow, WorkforceCapacityResponse } from '@/types/planning'
import { neutralizeSpreadsheetText, numericSpreadsheetValue } from '@/lib/spreadsheetText'

const CASE_ID = 'miniso-2026'
const HEADERS = ['case_id', 'plan_variant', 'period', 'business_unit', 'category_id', 'volume_change_pct', 'average_ticket_change_pct', 'gross_margin_delta_pp', 'opex_ratio_delta_pp'] as const
type PreviewSource = Exclude<PlanningInputSource, 'seed'>
export interface PlanningSession { rows: PlanningInputRow[]; variant: PlanVariant; source: PreviewSource; headcountRows: WorkforceCapacityInputRow[] }

function workforceInputRows(capacity: WorkforceCapacityResponse | null | undefined, variant: PlanVariant): WorkforceCapacityInputRow[] {
  return (capacity?.headcount_rows || []).filter((row) => row.plan_variant === variant && /^2026-(0[7-9]|1[0-2])$/.test(row.period)).map((row) => ({
    case_id: row.case_id,
    plan_variant: variant,
    period: row.period,
    business_unit: row.business_unit,
    role_group: row.role_group,
    planned_fte: row.planned_fte,
    monthly_loaded_cost: row.monthly_loaded_cost,
    provenance: 'synthetic_plan' as const,
  }))
}

export function parsePlanningInputCsv(csv: string): PlanningInputRow[] {
  const text = csv.replace(/^\uFEFF/, ''); const records: string[][] = []; let row: string[] = []; let field = ''; let quoted = false
  for (let i = 0; i < text.length; i += 1) { const c = text[i]; const n = text[i + 1]; if (c === '"') { if (quoted && n === '"') { field += '"'; i += 1 } else quoted = !quoted } else if (c === ',' && !quoted) { row.push(field); field = '' } else if ((c === '\n' || c === '\r') && !quoted) { if (c === '\r' && n === '\n') i += 1; row.push(field); if (row.some((value) => value !== '')) records.push(row); row = []; field = '' } else field += c }
  if (quoted) throw new Error('Malformed CSV: unterminated quoted field'); if (field !== '' || row.length) { row.push(field); records.push(row) }
  if (records.length < 2 || records[0].length !== HEADERS.length || records[0].some((value, index) => value !== HEADERS[index])) throw new Error('Template header mismatch')
  const driverFields = ['volume_change_pct', 'average_ticket_change_pct', 'gross_margin_delta_pp', 'opex_ratio_delta_pp'] as const
  return records.slice(1).map((values) => { if (values.length !== HEADERS.length) throw new Error('Invalid CSV row shape'); const [case_id, plan_variant, period, business_unit, category_id, volume, ticket, gm, opex] = values; let drivers: number[]; try { drivers = [volume, ticket, gm, opex].map((value, index) => numericSpreadsheetValue(value, driverFields[index])) } catch { throw new Error('Invalid CSV row values') } if (!case_id || !period || !business_unit || !category_id || !['base', 'upside', 'downside'].includes(plan_variant)) throw new Error('Invalid CSV row values'); return { case_id, plan_variant: plan_variant as PlanVariant, period, business_unit, category_id, volume_change_pct: drivers[0], average_ticket_change_pct: drivers[1], gross_margin_delta_pp: drivers[2], opex_ratio_delta_pp: drivers[3] } })
}

const NUMERIC_FIELDS = new Set<keyof PlanningInputRow>(['volume_change_pct', 'average_ticket_change_pct', 'gross_margin_delta_pp', 'opex_ratio_delta_pp'])
export function csvFromRows(rows: PlanningInputRow[]) {
  const escape = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`
  return [HEADERS.join(','), ...rows.map((row) => HEADERS.map((key) => {
    const value = row[key] as string | number
    return escape(NUMERIC_FIELDS.has(key) ? numericSpreadsheetValue(value, key) : neutralizeSpreadsheetText(String(value)))
  }).join(','))].join('\n')
}
function diagnostics(reason: unknown) { if (!(reason instanceof ApiError) || !Array.isArray(reason.details.diagnostics)) return []; return reason.details.diagnostics.slice(0, 50).map((item) => typeof item === 'object' && item !== null ? JSON.stringify(item) : String(item)) }

export function PlanningInputs({ dashboard, brand, market, session, workforceCapacity, onPreview, onDiscardAll }: { dashboard: DashboardResponse | null; brand: BrandFilter; market: MarketFilter; session: PlanningSession | null; workforceCapacity?: WorkforceCapacityResponse | null; onPreview: (next: DashboardResponse, nextSession: PlanningSession) => void; onDiscardAll: () => void }) {
  const [open, setOpen] = useState(false); const [variant, setVariant] = useState<PlanVariant>('base'); const [rows, setRows] = useState<PlanningInputRow[]>([]); const [headcountRows, setHeadcountRows] = useState<WorkforceCapacityInputRow[]>([]); const [source, setSource] = useState<PreviewSource>('editor'); const [error, setError] = useState<string | null>(null); const [errorDiagnostics, setErrorDiagnostics] = useState<string[]>([]); const [busy, setBusy] = useState(false)
  const requestId = useRef(0); const controllerRef = useRef<AbortController | null>(null); const fileRef = useRef<HTMLInputElement>(null)
  const visibleRows = useMemo(() => rows.filter((row) => row.plan_variant === variant), [rows, variant])
  const visibleHeadcountRows = useMemo(() => headcountRows.filter((row) => row.plan_variant === variant), [headcountRows, variant])
  useEffect(() => { if (session?.variant) setVariant(session.variant) }, [session?.variant])
  const showError = (reason: unknown, fallback: string) => { setError(reason instanceof Error ? reason.message : fallback); setErrorDiagnostics(diagnostics(reason)) }
  const openEditor = async () => { setOpen(true); setError(null); setErrorDiagnostics([]); if (session) { setRows(session.rows); setHeadcountRows(session.headcountRows); setVariant(session.variant); setSource(session.source); return }; setBusy(true); controllerRef.current?.abort(); const id = ++requestId.current; const controller = new AbortController(); controllerRef.current = controller; try { const capacityPromise = workforceCapacity ? Promise.resolve(workforceCapacity) : fetchOperatingPlan(CASE_ID, 'base', controller.signal).then((plan) => plan.workforce_capacity || plan.headcount_capacity || null); const [csv, capacity] = await Promise.all([fetchPlanningTemplate(CASE_ID, controller.signal), capacityPromise]); const parsed = parsePlanningInputCsv(csv); if (id === requestId.current) { setRows(parsed); setHeadcountRows(workforceInputRows(capacity, 'base')); setVariant('base'); setSource('editor') } } catch (reason) { if (id === requestId.current && (reason as Error).name !== 'AbortError') showError(reason, 'Unable to load planning template') } finally { if (id === requestId.current) setBusy(false) } }
  const download = () => { if (!rows.length) return; const blob = new Blob([csvFromRows(rows)], { type: 'text/csv;charset=utf-8' }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = 'PlanTerm_planning_inputs.csv'; anchor.click(); URL.revokeObjectURL(anchor.href) }
  const upload = async (file?: File) => { if (!file) return; controllerRef.current?.abort(); const id = ++requestId.current; const controller = new AbortController(); controllerRef.current = controller; setBusy(true); setError(null); setErrorDiagnostics([]); try { const result = await importPlanningInputs(CASE_ID, await file.text(), controller.signal); if (id === requestId.current) { setRows(result.rows); setSource('upload') } } catch (reason) { if (id === requestId.current && (reason as Error).name !== 'AbortError') showError(reason, 'Upload failed') } finally { if (id === requestId.current) setBusy(false) } }
  const edit = (row: PlanningInputRow, field: keyof Pick<PlanningInputRow, 'volume_change_pct' | 'average_ticket_change_pct' | 'gross_margin_delta_pp' | 'opex_ratio_delta_pp'>, value: string) => { setSource('editor'); setRows((current) => current.map((item) => item === row ? { ...item, [field]: Number(value) } : item)) }
  const editHeadcount = (row: WorkforceCapacityInputRow, field: keyof Pick<WorkforceCapacityInputRow, 'planned_fte' | 'monthly_loaded_cost'>, value: string) => { const numeric = value === '' ? 0 : Number(value); setHeadcountRows((current) => current.map((item) => item === row ? { ...item, [field]: numeric } : item)) }
  const selectVariant = (nextVariant: PlanVariant) => { setVariant(nextVariant); setHeadcountRows((current) => (current.length > 0 ? current.map((row) => ({ ...row, plan_variant: nextVariant })) : workforceInputRows(workforceCapacity, nextVariant))) }
  const apply = async () => { if (rows.length !== 252 || visibleHeadcountRows.length !== 72 || rows.some((row) => [row.volume_change_pct, row.average_ticket_change_pct, row.gross_margin_delta_pp, row.opex_ratio_delta_pp].some((value) => !Number.isFinite(value))) || headcountRows.some((row) => [row.planned_fte, row.monthly_loaded_cost].some((value) => !Number.isFinite(value)))) { setError('Complete all 252 planning rows and 72 H2 workforce rows with finite numeric values before preview.'); return } setBusy(true); setError(null); setErrorDiagnostics([]); controllerRef.current?.abort(); const id = ++requestId.current; const controller = new AbortController(); controllerRef.current = controller; try { const nextSession = { rows, variant, source, headcountRows }; const result = await previewDashboard(CASE_ID, rows, variant, source, brand, market, controller.signal); if (id === requestId.current) { onPreview(result, nextSession); setOpen(false) } } catch (reason) { if (id === requestId.current && (reason as Error).name !== 'AbortError') showError(reason, 'Preview failed') } finally { if (id === requestId.current) setBusy(false) } }
  const discardAll = () => { controllerRef.current?.abort(); requestId.current += 1; setOpen(false); setRows([]); setError(null); setErrorDiagnostics([]); onDiscardAll() }
  const context = dashboard?.category_detail_context || []
  return <><div className="planning-toolbar"><div><strong>Planning Inputs</strong><span>H2 category drivers · locked through 2026-06</span></div><button className="button button-primary" onClick={() => void openEditor()}><Pencil size={14} /> Open editor</button></div>
    {open && <div className="dialog-backdrop" role="dialog" aria-modal="true" aria-label="Planning Inputs"><div className="planning-dialog"><div className="dialog-header"><div><h2>Planning Inputs</h2><p>Complete 252-row matrix. Actual, Budget and H1 remain locked.</p></div><button className="icon-button" onClick={() => setOpen(false)} aria-label="Close"><X size={16} /></button></div>
      <div className="synthetic-disclosure">Synthetic planning input — not reported category data</div>
      <div className="planning-actions"><div className="variant-tabs">{(['base', 'upside', 'downside'] as PlanVariant[]).map((item) => <button key={item} className={variant === item ? 'active' : ''} onClick={() => selectVariant(item)}>{item}</button>)}</div><button className="button" onClick={download} disabled={!rows.length}><Download size={14} /> Download CSV</button><button className="button" onClick={() => fileRef.current?.click()}><Upload size={14} /> Upload CSV</button><input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={(event) => void upload(event.target.files?.[0])} /></div>
      <div className="locked-note">Locked horizon: through 2026-06 · Editable: 2026-07 to 2026-12 · Showing {visibleRows.length} rows for {variant} (252 total) · {visibleHeadcountRows.length} workforce rows</div>
      <div className="planning-content-scroll">
        {error && <div className="inline-error" role="alert"><div>{error}</div>{errorDiagnostics.length > 0 && <ul>{errorDiagnostics.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul>}</div>}
        {context.length > 0 && <div className="context-scroll"><table className="planning-context"><caption>Locked synthetic allocation context: H1 Actual, Prior Year, and FY Budget</caption><thead><tr><th>Business unit</th><th>Category</th><th>H1 Actual revenue</th><th>Prior Year revenue</th><th>FY Budget revenue</th><th>Basis</th></tr></thead><tbody>{context.map((item) => <tr key={`${item.business_unit}-${item.category_id}`}><td>{item.business_unit}</td><td>{item.category_name}</td><td>{item.h1_actual.revenue.toFixed(1)}</td><td>{item.h1_prior_year.revenue.toFixed(1)}</td><td>{item.fy_budget.revenue.toFixed(1)}</td><td>synthetic allocation</td></tr>)}</tbody></table></div>}
        <div className="matrix-scroll"><table className="planning-matrix"><thead><tr><th>Period</th><th>Business unit</th><th>Category</th><th>Volume %</th><th>Ticket %</th><th>GM delta pp</th><th>Opex delta pp</th></tr></thead><tbody>{visibleRows.map((row) => <tr key={`${row.plan_variant}-${row.period}-${row.business_unit}-${row.category_id}`}><td>{row.period}</td><td>{row.business_unit}</td><td>{row.category_name || row.category_id}</td>{(['volume_change_pct', 'average_ticket_change_pct', 'gross_margin_delta_pp', 'opex_ratio_delta_pp'] as const).map((field) => <td key={field}><input type="number" step="0.000001" value={row[field]} onChange={(event) => edit(row, field, event.target.value)} aria-label={`${field} ${row.period} ${row.category_id}`} /></td>)}</tr>)}</tbody></table></div>
        <div className="matrix-scroll"><table className="planning-matrix workforce-input-matrix"><caption>H2 workforce inputs · role-group level only · synthetic planning data</caption><thead><tr><th>Period</th><th>Business unit</th><th>Role group</th><th>Planned FTE</th><th>Monthly loaded cost</th><th>Provenance</th></tr></thead><tbody>{visibleHeadcountRows.map((row) => <tr key={`${row.plan_variant}-${row.period}-${row.business_unit}-${row.role_group}`}><td>{row.period}</td><td>{row.business_unit}</td><td>{row.role_group}</td><td><input type="number" min="0" step="1" value={row.planned_fte} onChange={(event) => editHeadcount(row, 'planned_fte', event.target.value)} aria-label={`planned_fte ${row.period} ${row.business_unit} ${row.role_group}`} /></td><td><input type="number" min="0" step="0.001" value={row.monthly_loaded_cost} onChange={(event) => editHeadcount(row, 'monthly_loaded_cost', event.target.value)} aria-label={`monthly_loaded_cost ${row.period} ${row.business_unit} ${row.role_group}`} /></td><td>{row.provenance}</td></tr>)}</tbody></table></div>
      </div>
      <div className="dialog-footer"><button className="button button-ghost" onClick={discardAll}><RotateCcw size={14} /> Discard All</button><button className="button button-primary" onClick={() => void apply()} disabled={busy || rows.length !== 252 || visibleHeadcountRows.length !== 72}><Save size={14} /> {busy ? 'Validating…' : 'Apply & preview'}</button></div>
    </div></div>}</>
}
