import { en, type EnglishCatalog } from './en'

const zhTWOverrides: Partial<Record<keyof EnglishCatalog, string>> = {
  language: '語言', languageChanged: '語言已切換為{language}', languageEnglish: 'English', languageZhCN: '简体中文', languageZhTW: '繁體中文',
  dashboardFilters: '儀表板篩選', brand: '品牌', market: '市場', allBrands: '全部品牌', allMarkets: '全部市場', chineseMainland: '中國大陸', overseas: '海外', globalTopToy: '全球 / TOP TOY', resetFilters: '重設篩選',
  kpis: '關鍵績效指標', h1Actual: '· H1實際', vsBudget: '對比預算', yoy: '年增率', notAvailable: '暫無資料',
  managementInsights: '管理洞察', monthlyRevenueTrend: '月度收入趨勢', rmbMillions: '人民幣百萬元', actual: '實際', budget: '預算', forecast: '預測', priorYear: '上年', reconciliationDifference: '勾稽差異',
  revenueBridge: '收入橋接', priceVolumeMix: '價格 / 數量 / 結構', profitBridge: '利潤橋接', operatingProfitBridge: '營業利潤橋接', grossProfit: '毛利', operatingProfit: '營業利潤', operatingMargin: '營業利潤率', businessUnitVariance: '業務單位差異', portfolioRollup: '組合彙總',
  governance: '治理', conclusionProvenance: '結論溯源', decisionLog: '決策日誌', addDecision: '新增決策', decisionContext: '2026 財年{variant}營運計畫結論', decisionUseVariant: '本次複核採用{variant}計畫變體', decisionRationale: '情境結論根據已確定的類別和現金橋接計算。', decisionTableContract: '情境決策表', cashBridgeContract: '現金橋接', reconciliationContract: '勾稽', evidenceRevenueDelta: '全年收入差異', evidenceOperatingProfitDelta: '全年營業利潤差異', evidenceRevenueDeltaFormula: '選定 2026 財年收入 - 基準 2026 財年收入', evidenceOperatingProfitDeltaFormula: '選定 2026 財年營業利潤 - 基準 2026 財年營業利潤', calculatedCategoryScenarioRollup: '計算所得類別情境彙總', statusProposed: '擬議', statusApproved: '已核准', statusSuperseded: '已取代', statusClosed: '已關閉', actionRegister: '行動登記', addAction: '新增行動', operatingPlanning: '營運計畫', workingCapitalCash: '營運資本與示例現金', forecastAccuracy: '預測準確度', workforceCapacity: '人力容量', scenarioDecisionTable: '情境決策表', planningInputs: '計畫輸入',
  openEditor: '開啟編輯器', close: '關閉', downloadCsv: '下載 CSV', uploadCsv: '上傳 CSV', discardAll: '全部捨棄', applyPreview: '套用並預覽', retry: '重試', loadingPlanning: '正在載入計畫案例…', dashboardUnavailable: '儀表板無法使用', localCase: '本地案例 · 無即時資料依賴', portfolioPlanning: '組合計畫與績效', workbenchSubtitle: 'FP&A 計畫與績效工作台', productVersion: 'PlanTerm v0.3', publicCaseStudy: '公開案例研究 · 非公司內部資料', footerWorkbench: 'FP&A 計畫與績效管理工作台', exportExcel: '匯出 Excel 管理包', scenarioComparison: '情境比較', productCategoryDetail: '產品類別明細',
  noAdverseVariance: '未發現不利的業務單位差異。', noDecisions: '本工作階段沒有記錄決策。', noScenarioRows: '沒有可用的情境決策列。', workingCapitalUnavailable: '此計畫變體沒有可用的營運資本列。', syntheticCategoryDisclosure: '合成計畫輸入 — 非報告類別資料', publicDisclosure: '公開報告資料錨定 H1 實際和上年資料。預算、預測、月度分配及業務單位成本/利潤視圖均明確標記為合成計畫假設。',
  planningAssumptions: '計畫假設', syntheticProfitAllocation: '合成利潤分配', officialDataSources: '官方資料來源', growth: '增長', ticket: '客單價', gmIndex: '毛利指數', omIndex: '營業利潤指數', selected: '已選', businessUnit: '業務單位', category: '類別', basis: '依據', syntheticAllocation: '合成分配',
  h2WorkforceInputs: 'H2 人力輸入 · 僅角色組級別 · 合成計畫資料', plannedFte: '計畫 FTE', monthlyLoadedCost: '月度全成本', roleGroup: '角色組', revenuePerFte: '收入 / FTE', portfolioTotal: '組合合計', portfolioPlannedFte: '組合計畫 FTE', requiredFte: '所需 FTE', capacityGap: '容量缺口', loadedCost: '全成本', variantDelta: '變體差異', productivityBasis: '生產力依據', lockedHorizon: '鎖定期至 2026-06；人力計畫可編輯期自 2026-07 開始',
  actualOperatingProfit: '實際營業利潤', budgetOperatingProfit: '預算營業利潤', opVariance: '營業利潤差異', ofOpVariance: '佔營業利潤差異', capex: '資本開支', otherCash: '其他現金', netCashChange: '現金淨變動', illustrativeClosingCash: '示例期末現金', minimumCashBuffer: '最低現金緩衝', headroom: '餘量', arDays: '應收賬款天數', inventoryDays: '庫存天數', apDays: '應付賬款天數', arBalance: '應收賬款餘額', inventory: '庫存', apBalance: '應付賬款餘額', nwc: '營運資本淨額',
  businessPartnering: '業務合作', remove: '移除', removeAction: '移除行動 {number}', scenarioOutcomes: '情境結果為合成計畫假設及計算差異。', noEligibilityStatus: '未提供適用性狀態', templateLoadFailed: '無法載入計畫模板', uploadFailed: '上傳失敗', completeMatrixError: '請在預覽前完成全部 252 條計畫記錄和 72 條 H2 人力記錄，並使用有限數值。', previewFailed: '預覽失敗',
  minisoPortfolioMvp: 'MINISO FP&A 組合 MVP', vsBase: '對比基準', points: '點', reconciled: '已勾稽', notEligible: '不適用', overCapacity: '容量過剩', zeroCapacity: '零容量', balanced: '平衡', favorable: '有利', unfavorable: '不利', neutral: '中性', pvmProfitEffect: 'PVM 利潤影響', opex: '營運費用', basePlan: '基準', upsidePlan: '上行情境', downsidePlan: '下行情境',
  errorInvalidExchange: '交易所無效', errorInvalidVenue: '市場場所無效', errorInvalidTicker: '代碼無效', errorAmbiguousTicker: '代碼需要明確市場場所', errorUnsupportedExchange: '不支援該交易所或市場場所', errorDependencyMissing: '未安裝可選資料提供方', errorNoData: '未找到公開資料', errorMalformedUpstream: '資料提供方返回了格式錯誤的資料', errorPeriodInconsistent: '資料提供方返回了不一致的期間', errorCurrencyMissing: '資料提供方未提供明確幣種', errorRateLimited: '已達到資料提供方速率限制', errorProviderTimeout: '資料提供方請求逾時', errorProviderUnavailable: '公開資料提供方不可用', errorValidation: '請求無法通過驗證', errorInternal: '發生內部錯誤', errorCaseNotFound: '找不到案例', errorReconciliation: '計算無法完成勾稽', errorRequest: '請求失敗',
  publicImport: '公開資料預覽', publicImportDescription: '查看白名單公開報告資料，不會修改本地 MINISO 案例。', exchange: '交易所', venue: '市場場所', ticker: '代碼', periodSelection: '期間', annual: '年度', quarterly: '季度', both: '年度及季度', submitPreview: '預覽公開資料', previewLoading: '正在載入公開資料…', previewResults: '預覽結果', publicData: '公開資料', statements: '報表', noStatements: '沒有符合所選期間的報表。', source: '來源', retrieved: '取得時間', asOf: '截至', filingDate: '申報日期', unit: '單位', nativeCurrency: '本幣', noFx: '不進行外匯換算。', publicOnly: '僅限公開報告資料。', notInternal: '非公司內部資料。', exchangeLse: 'LSE', exchangeAShare: 'A 股', exchangeHkex: '港股', exchangeUs: '美股', venueSse: '上交所 SSE', venueSzse: '深交所 SZSE', venueBse: '北交所 BSE', venueBseUnavailable: 'BSE 已在 API 中明確區分，但在啟用獲批准的資料提供方前不可用。', publicImportTickerPlaceholder: '例如 AAPL、VOD、0005 或 600519',
  eligible: '適用', noneIdentified: '未識別', portfolio: '組合',
  insightWatchTitle: '關注：{businessUnit} 低於年初至今計畫', insightBelowPlanMessage: '年初至今收入低於預算 {revenueVariance} 百萬元（{variancePercent}%）。收入驅動因素：{revenueDriver}。營業利潤驅動因素：{profitDriver}（影響 {profitEffect} 百萬元）；全年預測缺口為 {forecastGap}。', insightActionVolume: '按市場複核客流、轉化率和同店效率。', insightActionPrice: '檢查促銷深度、折扣和實際客單價。', insightActionMix: '將組合向更高毛利的品牌和地區傾斜。', insightActionGrossMargin: '複核折價、採購及毛利率相對計畫的實現情況。', insightActionOpex: '複核銷售及配送費用相對營運計畫的執行情況。',
  storeOperations: '門店營運', financeSupport: '財務 / 支援', revenuePerPlannedFte: '收入 / 計畫 FTE（人民幣百萬元 / FTE）', rmbMillionsUnlessStated: '除非另有說明，單位為人民幣百萬元',
  categoryIpToys: 'IP 與玩具', categoryHomeLifestyle: '家居與生活', categoryBeautyPersonalCare: '美妝與個人護理', categoryElectronicsAccessories: '電子與配件', categoryStationeryFoodOther: '文具、食品及其他', categoryBlindBoxesFigures: '盲盒與收藏玩偶', categoryBuildingBlocksKits: '積木與模型套件', categoryPlushDollsSculptures: '毛絨、玩偶與雕塑', categoryOtherToys: '其他玩具',
  syntheticAllocationDisclosure: '所有預算、預測、數量、客單價、成本和業務單位利潤分配均為示例，並非 MINISO 內部資料。客單價指數採用保持數量不變的調和歸一化；利潤分配指數採用收入份額加權歸一化。類別份額和情境驅動因素均為合成假設，從未聲稱是公開報告的類別資料。', kpiFormula: '{metric}：{actual} - {budget}；預測缺口 = 預測 - 財年預算', assumptionVersion: '假設版本', gitSha: 'Git 提交',
  commercialRevenueManagement: '商務 / 收入管理', sourcingMerchandising: '採購 / 商品管理', financeOperations: '財務 / 營運', sourceMiniso2025Form20F: 'MINISO 2025 年 20-F 表格', sourceMiniso2026H1: 'MINISO 2026 年上半年業績', sourceMiniso2026Q1: 'MINISO 2026 年第一季度業績', sourceMiniso2025H1: 'MINISO 2025 年上半年業績', sourceFy2025Scope: '2025 財年 IFRS 集團業績及分部披露', source2026Q2H1Scope: '2026 年第二季度及上半年 IFRS 業績和收入拆分', source2026Q1Scope: '2026 年第一季度 IFRS 業績和收入拆分', source2025H1Scope: '2025 年上半年 IFRS 業績和收入拆分',
  businessUnitChineseMainland: 'MINISO - 中國大陸', businessUnitOverseas: 'MINISO - 海外', businessUnitGlobalTopToy: 'TOP TOY - 全球',
}

// English is the deterministic fallback for non-primary copy; translated
// primary workflow strings above override it without creating a partial
// runtime catalog.
export const zhTW: Record<keyof EnglishCatalog, string> = { ...en, ...zhTWOverrides }
